project:
  type: website
  render:
    - index.qmd 
    - prerequisites.qmd
    - 1-basics/index.qmd
    - 1-basics/slides.qmd
    - 1-basics/tasks.qmd
    - 2-manipulation/index.qmd
    - 2-manipulation/slides.qmd
    - 2-manipulation/tasks.qmd
    - 3-visualisation/index.qmd
    - 3-visualisation/slides.qmd
    - 3-visualisation/tasks.qmd
    - 4-statistics/index.qmd
    - collaboration.qmd
    - ai.qmd
    - next-steps.qmd

format:
  html:
    toc: true
    toc-location: right
    author-meta: "Robin Lovelace & Juan Fonseca-Zamora"
    date-meta: "2025"
    copyright: "Â© 2025 Robin Lovelace & contributors"
    license: "CC BY-SA"
    theme: lux
    css: styles.css

website:
  sidebar:
    title: "<span class='intro-text'>Introduction to</span> <span class='ds-text'>Data Science</span>"
    style: "docked"
    search: true
    background: primary
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Prerequisites"
        href: prerequisites.qmd

      - section: "Basics"
        contents:
          - text: "About this section"
            href: 1-basics/index.qmd
          - text: "Tasks"
            href: 1-basics/tasks.qmd
      - section: "Manipulation"
        contents:
          - text: "About this section"
            href: 2-manipulation/index.qmd
          - text: "Tasks"
            href: 2-manipulation/tasks.qmd
      - section: "Visualisation"
        contents:
          - text: "About this section"
            href: 3-visualisation/index.qmd
          - text: "Tasks"
            href: 3-visualisation/tasks.qmd
      - section: "Statistics"
        contents:
          - text: "About this section"
            href: 4-statistics/index.qmd
      - text: "Collaboration"
        href: collaboration.qmd
      - text: "AI Tools"
        href: ai.qmd
      - text: "Next Steps"
        href: next-steps.qmd
