project:
  type: website
  render:
    - index.qmd 
    - prerequisites.qmd
    - github-copilot.qmd
    - practical.qmd
    - next-steps.qmd

format:
  html:
    toc: true
    toc-location: right
    author-meta: "Robin Lovelace & contributors"
    date-meta: "2025"
    copyright: "Â© 2025 Robin Lovelace"
    license: "CC BY-SA"
    theme: lux
    css: styles.css

website:
  sidebar:
    title: "<span class='intro-text'>Introduction to</span> <span class='ds-text'>Data Science</span>"
    style: "docked"
    search: true
    background: primary
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Prerequisites"
        href: prerequisites.qmd
      - text: "GitHub Copilot & AI"
        href: github-copilot.qmd
      - text: "Practical"
        href: practical.qmd
      - text: "Next Steps"
        href: next-steps.qmd 
